### ISSUE TITLE
Features for datapoints used in the paper

### ISSUE THREAD

**Issue by meghbhalerao** [muradtuk/Provable-Data-Subset-Selection-For-Efficient-Neural-Network-Training#1]
Dear Authors, 
Thank you for the work and open source code.
I had a question, what are the features that are being used for the datapoints P while doing sensitivity calculation? I could not find a place which mentions this in the paper? Or is everything being done in the original image space? 
I see that in the code here - https://github.com/muradtuk/Provable-Data-Subset-Selection-For-Efficient-Neural-Network-Training/blob/main/AproxMVEE.py#L270 - P is just being defined as a toy dataset, but I was wondering if there is any place where I can find how are the image features being extracted?
Thanks for your time and help!
Megh

**Comment by muradtuk** [comment]
Dear Megh, 

Thank you for your interest in our paper and open-source code. 
We applied a PCA dimensionality reduction on the flattened images to obtain our data points, for ease of explanation, let's call such a matrix P. 

Based on our theory, we modified P modified as follows: we appended a column of the square norm of each point p in P to its corresponding row as well as a column of ones. From here on out, we computed the matrix representing the Lowner ellipsoid of the convex hull of P.

This way, we can compute the sensitivities (i.e., importances) of the points of P which will be used as a measure of importance with respect to the original images.

We hope this helps, and please feel free to contact us if you have any more questions.

Best regards,
The Authors.

**Comment by meghbhalerao** [comment]
Hi, thank you for sharing the information.
I was wondering if there is any place where I can get some more details regarding this, such as -
1. What dimensionality was used while doing the PCA dimension reduction for each of the datasets that are reported in the paper?
2. Also, for getting the lower ellispsoid of the convex hull, is it this function in the code which does it - https://github.com/muradtuk/Provable-Data-Subset-Selection-For-Efficient-Neural-Network-Training/blob/main/AproxMVEE.py#L191? Please do let me know if I am wrong.
3. Also, just to clarify, once we have P, we do some processing on it to get the lower-ellipsoid-of-convex-hull-of-P (lets call this LECHP), which is basically a matrix of dimension `n x feat_dim`, where n is the number of points in the dataset, i.e. in the whole dataset? Is the code mentioned in the above point 2 doing this?
Thank you again for your time and I look forward to hearing from you.
Megh

Edit: Sorry, so I am not very familiar with the concept of MVEE, so my point 3 maybe would not make sense, but keeping it incase there is some information in it. So basically once we have the P matrix (after PCA and adding the 2 extra columns, call this D \in n * d), the MVEE representation is calculated (minimum or maximum volume?) and that MVEE representation is useful for the sensitivity calculation, but the features will still be the D \in n* d.

**Comment by muradtuk** [comment]
Hi Megh,

Thank you again for your interest in our paper. As for your questions:

1. Throughout our experiments, we have used 500 dimensions in the context of PCA.
2. To obtain the Lowner ellipsoid, we have used the compute_approximated_MVEE function. For a better understanding of how we use this ellipsoid, we kindly refer you to https://github.com/muradtuk/Provable-Data-Subset-Selection-For-Efficient-Neural-Network-Training/blob/5cccffe3ca37d17afd9143d1ce48432017931355/AproxMVEE.py#L109 and https://github.com/muradtuk/Provable-Data-Subset-Selection-For-Efficient-Neural-Network-Training/blob/5cccffe3ca37d17afd9143d1ce48432017931355/CORESET.py#LL31C18. 
3. To avoid numerical instabilities, when computing the sensitivities, we did not concatenate the columns of 1s since from the perspective of MVEE, the length of that axis is basically zero (due to that feature being constant). This is still theoretically sound and by doing so, we did not harm the theoretical guarantees of such an ellipsoid. 
So the MVEE will be represented by a matrix (LECHP) of dimensionality of 501 x 501, where such a matrix is multiplied by the projected points of P -- let's call the result of this multiplication  U (a matrix of dimension n x 501). The sensitivities of the original images are then the norms of U.

We hope this clarifies the confusion, and again, please feel free to contact us with respect to any questions you have.

Kind regards,
The authors.
